ANDROID: incfs: use new ->i_state accessors
Direct access to ->i_state now results in a build error. Instead, the
new accessors should be used introduced in commit 18c61399f6b9 ("xfs:
use the new ->i_state accessors"). This fixes build errors such as:

  common/fs/incfs/pseudo_files.c:1351:21: error: invalid operands to binary expression ('struct inode_state_flags' and 'int')
   1351 |         if (inode->i_state & I_NEW)
        |

Cc: Paul Lawrence <paullawrence@google.com>
Fixes: 2ed81b4bef9b ("fs: make plain ->i_state access fail to compile")
Change-Id: I6e1ac870bcfa1542d5b3349a557477a2c720b0be
Signed-off-by: Carlos Llamas <cmllamas@google.com>