MGS-6622 [#imx-2974] Fix build error using lower version toolchain
Fix following build error using 5.10, 5.4 or lower version toolchain.
5.15 toolchain is OK.

drivers/mxc/gpu-viv/hal/os/linux/kernel/allocator/default/gc_hal_kernel_allocator_gfp.c: In function ‘_GFPAlloc’:
drivers/mxc/gpu-viv/hal/os/linux/kernel/allocator/default/gc_hal_kernel_allocator_gfp.c:568:9: error: a label can only be part of a statement and a declaration is not a statement
568 | void *addr = NULL;

Signed-off-by: Guangliu Ding <guangliu.ding@nxp.com>
(cherry picked from commit 5654a6bc75d4f276aa0ae4c6784cc96c3e8c2e3f nxp-kernel)
Signed-off-by: Wen-chien Jesse Sung <jesse.sung@canonical.com>