ANDROID: GKI: add arch dependency for IOMMU_SVA
Upstream only selects IOMMU_SVA for x86 and arm64. Using it for other
architectures breaks the build because commit e37d5a2d60a3 ("iommu/sva:
invalidate stale IOTLB entries for kernel address space") introduced a
call to mmu_notifier_arch_invalidate_secondary_tlbs() and its prototype
is missing for these other archs:

  common/drivers/iommu/iommu-sva.c:340:3: error: call to undeclared function 'mmu_notifier_arch_invalidate_secondary_tlbs' [...]
    340 |  mmu_notifier_arch_invalidate_secondary_tlbs(iommu_mm->mm, start, end);
        |  ^

This is because only certain architecture specific tlbflush.h header
files include <linux/mmu_notifier.h> where the prototype lives. The
correct fix would be to add this header file to iommu-sva.c, and I'll
attempt to upstream that. However, this is an OOT breakage and it might
be hard convince upstream. See [1].

For the time being, let's restrict the IOMMU_SVA selection to upstream
supported architectures. This allows us to move on with mainline merges.
This can be reverted if an alternative fix lands.

Cc: Isaac J. Manjarres <isaacmanjarres@google.com>
Link: https://lore.kernel.org/all/20260105190747.625082-1-cmllamas@google.com/ [1]
Fixes: 06f8e52b34f3 ("ANDROID: GKI: Introduce GKI_HIDDEN_IOMMU_CONFIGS")
Change-Id: I2bd82296a0a275a414bd1133da8bf122e17268a4
Signed-off-by: Carlos Llamas <cmllamas@google.com>