LF-1011-26 arm: imx: pm-imx7: fix build break when calling of_flat_dt_match
Old API was hiddened from user.

../arch/arm/mach-imx/pm-imx7.c: In function ‘imx7_dt_find_lpsram’:
../arch/arm/mach-imx/pm-imx7.c:891:6: error: implicit declaration of function ‘of_flat_dt_match’ [-Werror=implicit-function-declaration]
  891 |  if (of_flat_dt_match(node, low_power_ocram_match)) {
      |      ^~~~~~~~~~~~~~~~

Signed-off-by: Dong Aisheng <aisheng.dong@nxp.com>
(cherry picked from commit 078df81671cd54b33d4eeba548407106be293a96 nxp-kernel)
Signed-off-by: Wen-chien Jesse Sung <jesse.sung@canonical.com>