UBUNTU: SAUCE: mxc: gpu-viv: change 3 functions to static type
BugLink: https://warthogs.atlassian.net/browse/LUVN-754 ([i.MX6Q] Missing /dev/dri/card0 node (LUVN-754))

Building the driver will introduce the error as below:
error: no previous prototype for ‘_RemoveRecordFromProcesDB’ [-Werror=missing-prototypes]

Those functions are not called outside, no need to be global.

Signed-off-by: Hui Wang <hui.wang@canonical.com>
Signed-off-by: Wen-chien Jesse Sung <jesse.sung@canonical.com>