media: v4l2: export video_usercopy function
export video_usercopy function to fix following build error.

ERROR: "video_usercopy" [drivers/media/platform/mxc/capture/mxc_v4l2_capture.ko] undefined!
../scripts/Makefile.modpost:105: recipe for target 'modules-modpost' failed
make[2]: *** [modules-modpost] Error 1
/u/home/r63905/ProjectA/Dash_Linux_next2/dash-linux-devel/Makefile:1305: recipe for target 'modules' failed
make[1]: *** [modules] Error 2
make[1]: *** Waiting for unfinished jobs....

Signed-off-by: Robby Cai <robby.cai@nxp.com>
(cherry picked from commit b888f73209424d95fd8d6a92441aa74b0050327f nxp-kernel)
Signed-off-by: Wen-chien Jesse Sung <jesse.sung@canonical.com>