fec_uio: fix implicit declaration
Fix the build error:

  /lmp/source/real-main/build-lmp/tmp-lmp/work-shared/imx8mm-lpddr4-evk/kernel-source/drivers/net/ethernet/freescale/fec_uio.c: In function 'fec_enet_uio_probe':
  /lmp/source/real-main/build-lmp/tmp-lmp/work-shared/imx8mm-lpddr4-evk/kernel-source/drivers/net/ethernet/freescale/fec_uio.c:573:9: error: implicit declaration of function 'pinctrl_pm_select_default_state' [-Werror=implicit-function-declaration]
    573 |         pinctrl_pm_select_default_state(&pdev->dev);
        |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Signed-off-by: Daiane Angolini <daiane.angolini@foundries.io>
Acked-by: Jason Liu <jason.hui.liu@nxp.com>
(forward ported from commit 8ca4486e41a6bf8847e4f6ab99686fe3d3e8e2ba nxp-kernel)
Signed-off-by: Wen-chien Jesse Sung <jesse.sung@canonical.com>