hwmon: max17135: Added linux/mod_devicetable.h
This patch added linux/mod_devicetable.h to fix the compilation error.

drivers/hwmon/max17135-hwmon.c:57:40: error: array type has incomplete element type ‘struct platform_device_id’
 static const struct platform_device_id max17135_sns_id[] = {
                                        ^~~~~~~~~~~~~~~
drivers/hwmon/max17135-hwmon.c:57:40: warning: ‘max17135_sns_id’ defined but not used [-Wunused-variable]
scripts/Makefile.build:303: recipe for target 'drivers/hwmon/max17135-hwmon.o' failed
make[2]: *** [drivers/hwmon/max17135-hwmon.o] Error 1

Signed-off-by: Vipul Kumar <vipul_kumar@mentor.com>
(cherry picked from commit 5d19850d2c1ba09deac46669fe69a825fc780670 nxp-kernel)
Signed-off-by: Wen-chien Jesse Sung <jesse.sung@canonical.com>