MLK-21876-10 gpu: drm: ipu: fix headfile reference issue (part2)
../drivers/gpu/drm/imx/ipuv3/ipuv3-plane.c:17:21: fatal error: imx-drm.h: No such file or directory
 #include "imx-drm.h"

Signed-off-by: Dong Aisheng <aisheng.dong@nxp.com>
(cherry picked from commit d9f84b7f04ac30b6bb35c3b75245559e81776a7b nxp-kernel)
Signed-off-by: Wen-chien Jesse Sung <jesse.sung@canonical.com>