MGS-7375 [#nxp] initialize the struct
fix below build error when CONFIG_KASAN=y

drivers/gpu/arm/midgard/mali_kbase_ioctl_helpers.h:77:22: note: ‘param’ declared here
   77 |                 type param;                                                            \
      |                      ^~~~~
drivers/gpu/arm/midgard/mali_kbase_core_linux.c:1666:17: note: in expansion of macro ‘KBASE_HANDLE_IOCTL_INOUT’
 1666 |                 KBASE_HANDLE_IOCTL_INOUT(KBASE_IOCTL_VERSION_CHECK_RESERVED,
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~
In function ‘instrument_copy_from_user_before’,
    inlined from ‘_copy_from_user’ at ./include/linux/uaccess.h:148:3,
    inlined from ‘copy_from_user’ at ./include/linux/uaccess.h:183:7,
drivers/gpu/arm/midgard/mali_kbase_core_linux.c:1672:3:
./include/linux/kasan-checks.h:38:27: error: ‘param’ may be used uninitialized [-Werror=maybe-uninitialized]
   38 | #define kasan_check_write __kasan_check_write
./include/linux/instrumented.h:129:9: note: in expansion of macro ‘kasan_check_write’
  129 |         kasan_check_write(to, n);
      |         ^~~~~~~~~~~~~~~~~

Signed-off-by: Jiyu Yang <jiyu.yang@nxp.com>
(cherry picked from commit 6af0984c5de4192d6f1c0fff942577217406f006 nxp-kernel)
Signed-off-by: Wen-chien Jesse Sung <jesse.sung@canonical.com>