MA-20999 i2c: imx: flexio: Fix fall-through warning for Clang
Fix below build warning:

drivers/i2c/busses/i2c-flexio.c:411:3: error: unannotated
fall-through between switch labels [-Werror,-Wimplicit-fallthrough]

Signed-off-by: Zhipeng Wang <zhipeng.wang_1@nxp.com>
Signed-off-by: Jindong Yue <jindong.yue@nxp.com>
Reviewed-by: Alice Guo <alice.guo@nxp.com>
(cherry picked from commit c8d51b024e8ff4c37dc0a503bdd702110297a44d nxp-kernel)
Signed-off-by: Wen-chien Jesse Sung <jesse.sung@canonical.com>