MA-22965 neutron: Initialize data_ddr to avoid build error.
error log:
error: variable 'data_ddr' is uninitialized when used here [-Werror,-Wuninitialized]
	ret = neutron_rproc_elf_load(rproc, buf->firmware_p, data_ddr, 0x1);
								^~~~~~~~

Change-Id: If3852cf0214f594b7fc6bcc147226558ecb75ec0
Signed-off-by: Zhipeng Wang <zhipeng.wang_1@nxp.com>
(cherry picked from commit f04c1b2802c31ab6e4adfabcba933034a7553156 nxp-kernel)
Signed-off-by: Wen-chien Jesse Sung <jesse.sung@canonical.com>