dt-bindings: fix path to imx93-power.h
Fix the following in "make -j 8 DT_CHECKER_FLAGS=-m dt_binding_check DT_SCHEMA_FILES=phy/":

Documentation/devicetree/bindings/phy/fsl,imx93-mipi-dphy.example.dts:19:18:
fatal error: 'dt-bindings/power/imx93-power.h' file not found
        #include <dt-bindings/power/imx93-power.h>
                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Signed-off-by: Vladimir Oltean <vladimir.oltean@nxp.com>
(cherry picked from commit d5c4098529168fc3ad6637694b8e16f9dab59c26 nxp-kernel)
Signed-off-by: Wen-chien Jesse Sung <jesse.sung@canonical.com>