LF-1011-30 arm: imx: pm-imx6: fix build break when calling of_flat_dt_match
Old API was hiddened from user.

../arch/arm/mach-imx/pm-imx6.c: In function ‘imx6_dt_find_lpsram’:
../arch/arm/mach-imx/pm-imx6.c:973:6: error: implicit declaration of function ‘of_flat_dt_match’ [-Werror=implicit-function-declaration]
  973 |  if (of_flat_dt_match(node, low_power_ocram_match)) {

Signed-off-by: Dong Aisheng <aisheng.dong@nxp.com>
(cherry picked from commit a1e460cb1a186206a131f62e299eee18a20745aa nxp-kernel)
Signed-off-by: Wen-chien Jesse Sung <jesse.sung@canonical.com>