net: sdk_fman: add "void" to function prototypes with no argument
clang-16 fails to build with errors like this:

drivers/net/ethernet/freescale/sdk_fman/Peripherals/FM/Port/fm_port.c:6380:27:
error: a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
void FM_PORT_Dsar_DumpRegs()
                          ^
                           void

Signed-off-by: Vladimir Oltean <vladimir.oltean@nxp.com>
Reviewed-by: Camelia Groza <camelia.groza@nxp.com>
(cherry picked from commit 2ef65875ed6f5ad4adafa756609756745c17dbc5 nxp-kernel)
Signed-off-by: Wen-chien Jesse Sung <jesse.sung@canonical.com>