MA-22143-1 pwm: adp5585: Fix typo in adp5585_of_match
Fix below build error when building it as a module:
  drivers/pwm/pwm-adp5585.c:215:25: error: use of undeclared identifier
  'adp5585_of_match'; did you mean 'adp5585_pwm_of_match'?
  MODULE_DEVICE_TABLE(of, adp5585_of_match);

Signed-off-by: Jindong Yue <jindong.yue@nxp.com>
Reviewed-by: Clark Wang <xiaoning.wang@nxp.com>
(cherry picked from commit 1cfdc29e9445b4ecbc3f59f4f4f71aef4dceaaac nxp-kernel)
Signed-off-by: Wen-chien Jesse Sung <jesse.sung@canonical.com>