LF-125 irqchip: irq-imx-gpcv2: Fix build error of nosmp
Fix below build error when CONFIG_SMP is NOT selected:

drivers/irqchip/irq-imx-gpcv2.c: In function "imx_gpcv2_wake_request_fixup":
drivers/irqchip/irq-imx-gpcv2.c:123:2: error: implicit declaration of function
"set_smp_cross_call" [-Werror=implicit-function-declaration]
  123 |  set_smp_cross_call(imx_gpcv2_raise_softirq);
      |  ^~~~~~~~~~~~~~~~~~
cc1: some warnings being treated as errors
make[3]: *** [drivers/irqchip/irq-imx-gpcv2.o] Error 1

Signed-off-by: Anson Huang <Anson.Huang@nxp.com>
Reviewed-by: Robin Gong <yibin.gong@nxp.com>
(cherry picked from commit c07fccca0591e5b5a8fa681eb73fb3df63767e9f nxp-kernel)
Signed-off-by: Wen-chien Jesse Sung <jesse.sung@canonical.com>