ANDROID: ABI: Update pixel symbol list
Changes:
1 function symbol(s) added
  'void arch_touch_nmi_watchdog()'

After applying https://r.android.com/c/4128114, Pixel failed to build:

ERROR: modpost: "arch_touch_nmi_watchdog" [...8250_base.ko] undefined!
...
Target //private/devices/google/muzel:muzel/dist failed to build

It seems the symbol `arch_touch_nmi_watchdog` has been trimmed.  Add the
symbol to the list.

Bug: 484396742
Bug: 544573018
DISABLE_TOPIC_PROTECTOR
Change-Id: I4cedc80f57e47f3b14eb9ba109702c335499308c
Signed-off-by: Tzung-Bi Shih <tzungbi@google.com>
(cherry picked from commit a9f45c382a77076062801a9379c22858e4bb903a)