fsl_qbman: add explicit fallthrough to qman_destroy_fq()
Fixes clang-16 build breakage:

drivers/staging/fsl_qbman/qman_high.c:1723:2: error: unannotated fall-through between switch labels [-Werror,-Wimplicit-fallthrough]
        case qman_fq_state_oos:
        ^
drivers/staging/fsl_qbman/qman_high.c:1723:2: note: insert '__attribute__((fallthrough));' to silence this warning
        case qman_fq_state_oos:
        ^
        __attribute__((fallthrough));
drivers/staging/fsl_qbman/qman_high.c:1723:2: note: insert 'break;' to avoid fall-through
        case qman_fq_state_oos:
        ^
        break;

Signed-off-by: Vladimir Oltean <vladimir.oltean@nxp.com>
Reviewed-by: Camelia Groza <camelia.groza@nxp.com>
(cherry picked from commit 5a641fff57e8c7779588c82f891231edd2f3de7d nxp-kernel)
Signed-off-by: Wen-chien Jesse Sung <jesse.sung@canonical.com>