MA-22955 PCI: imx6: Add __maybe_unused to avoid build errors
The __setup macro does not always trigger the compiler to treat the
function as "used". The following build error may be encountered:

drivers/pci/controller/dwc/pci-imx6.c:1847:19: error: unused function 'imx6_pcie_compliance_test_enable' [-Werror,-Wunused-function]
 1847 | static int __init imx6_pcie_compliance_test_enable(char *str)
      |                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.

Change-Id: Ie3f8cdf1cd624b29e2df8867d063ad9fb1fdea8b
Signed-off-by: Zhipeng Wang <zhipeng.wang_1@nxp.com>
(cherry picked from commit 3db13005aa1532ccfdf53c42590c6c0095610d51 nxp-kernel)
Signed-off-by: Wen-chien Jesse Sung <jesse.sung@canonical.com>