LF-1162-10 gpu: drm: bridge: it6263: include correct headfile for DRM_ERROR
../drivers/gpu/drm/bridge/it6263.c: In function ‘it6263_bridge_attach’:
../drivers/gpu/drm/bridge/it6263.c:729:3: error: implicit declaration of function ‘DRM_ERROR’; did you mean ‘DDC_ERROR’? [-Werror=implicit-function-declaration]
  729 |   DRM_ERROR("Fix bridge driver to make connector optional!");

Signed-off-by: Dong Aisheng <aisheng.dong@nxp.com>
(cherry picked from commit 20203f5fac4a380a40c449e6c8bfddff40800110 nxp-kernel)
Signed-off-by: Wen-chien Jesse Sung <jesse.sung@canonical.com>