MA-22143-5 drm/imx: dpu95-bliteng: Import DMA_BUF namespace
Fix below build error when building it as a module:
  ERROR: modpost: module imx95-dpu-drm uses symbol dma_buf_get
from namespace DMA_BUF, but does not import it.

Signed-off-by: Jindong Yue <jindong.yue@nxp.com>
Reviewed-by: Guangliu Ding <guangliu.ding@nxp.com>
(cherry picked from commit f411e1577f356d554c03dd001873065cb0b53c4f nxp-kernel)
Signed-off-by: Wen-chien Jesse Sung <jesse.sung@canonical.com>