LF-665-25 ARM: multi_v7_defconfig: disable CONFIG_DRM_TEGRA temporarily
We reverted this patch "drm/tegra: Move drm_dp_link helpers to Tegra DRM" which
is incompatible with current tegra drm drivers.
Have to disable it, otherwise will meet below build break.

../drivers/gpu/drm/tegra/sor.c: In function ‘tegra_sor_filter_rates’:
../drivers/gpu/drm/tegra/sor.c:625:24: error: ‘struct drm_dp_link’ has no member named ‘num_rates’; did you mean ‘num_lanes’?
625 |  for (i = 0; i < link->num_rates; i++) {
  |                        ^~~~~~~~~
  |                        num_lanes
../drivers/gpu/drm/tegra/sor.c:626:17: error: ‘struct drm_dp_link’ has no member named ‘rates’; did you mean ‘rate’?
626 |   switch (link->rates[i]) {

Signed-off-by: Dong Aisheng <aisheng.dong@nxp.com>
(cherry picked from commit 84c969cde1b9fb5a257d11e431281fc76ddb0b55 nxp-kernel)
Signed-off-by: Wen-chien Jesse Sung <jesse.sung@canonical.com>