LF-6783: drm: imx_mhdp: fix build error
Fix the build error for LF_NEXT_L5.19_RC7_20220719

CC [M] drivers/gpu/drm/imx/mhdp/cdns-mhdp-imxdrv.o
drivers/gpu/drm/imx/mhdp/cdns-mhdp-imxdrv.c:103:19: error: ‘MEDIA_BUS_FMT_RGB101010_1X30’ undeclared here (not in a function)
103 | .video_format = MEDIA_BUS_FMT_RGB101010_1X30,

Signed-off-by: Sandor Yu <Sandor.yu@nxp.com>
Reviewed-by: Robby Cai <robby.cai@nxp.com>
(cherry picked from commit 989cded4812e4a09949aba58c16324ff5b4aa3e6 nxp-kernel)
Signed-off-by: Wen-chien Jesse Sung <jesse.sung@canonical.com>