ANDROID: GKI: update protected exports list
Running tools/bazel run //common:kernel_aarch64_abi_update resulted
in below error. So update protected exports list.

ERROR: protected exports list must be updated before updating ABI definition.
To update, execute 'tools/bazel run @@//common:kernel_aarch64_abi_update_protected_exports'.

Bug: 537587702
Bug: 542819422
Change-Id: I3a64ba31802cbaa4f19768b595eb001823e90624
Signed-off-by: Sooyong Suk <s.suk@samsung.corp-partner.google.com>
(cherry picked from commit 08a9960b6868a1adac8d241ba4116d233db0a349)
Signed-off-by: Sooyong Suk <s.suk@samsung.corp-partner.google.com>