MLK-23547: ASoC: SOF: Use machine_drv_name on OF platforms
On OF platforms information about machine driver is stored
in sof_pdata->machine_drv_name.

Without this SOF probe fails with:
error: no matching ASoC machine driver found - aborting probe

Signed-off-by: Daniel Baluta <daniel.baluta@nxp.com>
(forward ported from commit 3c1577fad1d1bdf6bd9b555263dbcc5bb0a852e7 nxp-kernel)
Signed-off-by: Wen-chien Jesse Sung <jesse.sung@canonical.com>