MA-21052-4 gpu: drm: bridge: cadence: Add DRM_DISPLAY_HDMI_HELPER for DRM_CDNS_MHDP
Fix build error:
ERROR: modpost: "drm_hdmi_avi_infoframe_colorimetry" [drivers/gpu/drm/bridge/cadence/cdns_mhdp_drmcore.ko] undefined!
ERROR: modpost: "drm_hdmi_infoframe_set_hdr_metadata" [drivers/gpu/drm/bridge/cadence/cdns_mhdp_drmcore.ko] undefined!

Change-Id: I07a891329fd9943e4877f3ed64ac059caf7e9482
Signed-off-by: Zhipeng Wang <zhipeng.wang_1@nxp.com>
(cherry picked from commit 08e617d00fdb165db0e4891852f53950250bc5bd nxp-kernel)
Signed-off-by: Wen-chien Jesse Sung <jesse.sung@canonical.com>