MGS-6197 [#imx-2532] fix compile error when DEBUG enable
ERROR: modpost: "gcoOS_DebugTrace" [gpu-viv6/driver/galcore.ko] undefined!
ERROR: modpost: "gcoOS_DebugBreak" [gpu-viv6/driver/galcore.ko] undefined!
ERROR: modpost: "gcoOS_Verify" [gpu-viv6/driver/galcore.ko] undefined!

Signed-off-by: Jiyu Yang <jiyu.yang@nxp.com>
(cherry picked from commit a14cef3a23273a747688176c1200bf8755a9235b nxp-kernel)
Signed-off-by: Wen-chien Jesse Sung <jesse.sung@canonical.com>