MLK-13470 mfd: max17135: export symbols to fix build error as a module
export symbols to fix build error as a module:

ERROR: "max17135_reg_read" [drivers/hwmon/max17135-hwmon.ko] undefined!

Signed-off-by: Julien Olivain <julien.olivain@nxp.com>
Acked-by: Robby Cai <robby.cai@nxp.com>
(cherry picked from commit 6852169e507b76c03a05d8f68ea96dbe1b4cde28 nxp-kernel)
Signed-off-by: Wen-chien Jesse Sung <jesse.sung@canonical.com>